language: go
go:
- 1.3.1
- tip
env:
- PATH=$HOME/gopath/bin:$PATH
script:
- make dep
- make build
- make test
notifications:
  email: false
  slack:
    secure: VzX3ebaxXn5fAupPoqfeqldN++sKW674b9IX52a1SbAurqw+o1yuu+pcAu9SL3YkZEGltWqDpH1m9xFMXzfJzDPYj1BFTds4q742Asr6oIIWyfsbuuU5atyIK6F04bT3hH1UXGWoUvGab1Luj7ZhJYUXw1sQ0cDgeaIcH0155rs=
